# numpy

### creating a numpy array

### 1. Give a list as input 
### np.array([list])
### list must be homogeneous or all elemnets should be of same data type.


In [2]:
import numpy as np

In [11]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


## 2. np.zeros

### np.zeros((dimension)) will return the desired array all with zeros with given or specified dimensions.
### simply returns an array with zeroes

In [19]:
arr=np.zeros((3,3))
print(arr)

count=0
for row in range(len(arr)):
    for col in range((len(arr[0]))):
        count=count+1
        arr[row][col]=count
print("array created using zeros : ")
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array created using zeros : 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## Shape 

#### Shape returns the dimensions of array such as m,n in m X n dimension.
### dim returns the dimensionality means how many variable are there in dimensions.i.e 1D or 2D or 3D.

In [10]:
import numpy as np

#1-D Numpy Array
arr1D=np.array([1,2,3])

#2-D Numpy Array
arr2D=np.array( [[1,2,3],[4,5,6]])

#3-D Numpy Array
arr3D=np.array( [ [[1,2,3]] ])

print(" Dimension : {a}".format(a=arr1D.ndim))
print(" Dimension : {a}".format(a=arr2D.ndim))
print(" Dimension : {a}".format(a=arr3D.ndim))

print(" Dimesnions: {a}".format(a=arr1D.shape))
print(" Dimensions : {a}".format(a=arr2D.shape))
print(" Dimensions : {a}".format(a=arr3D.shape))


 Dimension : 1
 Dimension : 2
 Dimension : 3
 Dimesnions: (3,)
 Dimensions : (2, 3)
 Dimensions : (1, 1, 3)


In [20]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(" shape of array is : {a} ".format(a=arr.shape))

 shape of array is : (3, 3) 


# Reshape

### Reshape lets us change the dimesnion of an array to desired dimension. i,e in m X n can be made a X b.

### Reshape is only possible if the multiplying the dimesnion is equal to the number of Total elements.

In [21]:
# ReShape
# Reshape is only possible if the multiplying the dimesnion is equal to the number of Total elements.
print(arr.reshape((9,1)))
print(arr.reshape((1,9)))


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[1 2 3 4 5 6 7 8 9]]


### dtype :

### Gives the datatype of array elements.

In [24]:
print("arr : {a} ".format(a=arr.dtype ))

arr : int32 


## Changing Data Types

#### Changing DataType from int32 to float32 or int64 or float 64 .
#### 32 is nothing but 32 bits are there for that elements .
#### 64 means 64 bits are there for those array elements.

### astype('data type') will return us a data type changed array.

In [28]:
changedArr=arr.astype('float32')
print(arr.dtype)
print(arr)
print(changedArr.dtype)
print(changedArr)

int32
[[1 2 3]
 [4 5 6]
 [7 8 9]]
float32
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## All Array Creation Methods.

## np.ones()

### np.ones(dimensionality)
### np.ones((m,n))
### returns an array with only ones

In [33]:
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## np.full


### np.full((dimensionality),val)
### only given value will be there as a element in the array.

In [39]:
arr=np.full((2,3),14)
arr

array([[14, 14, 14],
       [14, 14, 14]])

## np.eye()

### Will Return an Identity Array.
### np.eye(dimesnionality)

In [35]:
I=np.eye((5))
print(" Dimesions are  : ", I)
print(" Data Type  : ",I.dtype)

 Dimesions are  :  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
 Data Type  :  float64


## np.arange()

### np.arange(start,end,step)
### step will be added until ele crosses end .
### every will be in start to end range.

In [41]:
arr=np.arange(1,30,5)
arr

array([ 1,  6, 11, 16, 21, 26])

## np.linspace()

### np.linspace(start,end ,no of elements you want)
### it will return an equal spaced elements as array.

In [42]:
arr=np.linspace(1,100,5)
arr

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

## np.flatten()

### converts any dimensional array into one Dimensional

In [47]:
arr=np.array([[1,2,3],[4,5,6]])
arr=arr.flatten()
arr

array([1, 2, 3, 4, 5, 6])

# Indexing

## . Normal Indexing and slicing in both numpy arrays and lists are same .

# 2. Fancy Indexing

### Fancy Indexing means we can select mutiple elements 
### or Index Multiple Elements at same time.

# arr[[list of indices]]

In [49]:
arr=np.array([10,20,30,40,50])
print(arr[[1,2,3]])

[20 30 40]


# 3.Boolean Indexing

### Selects elements only which satisfies condition.

In [50]:
arr=np.array([10,2,30,40,50])
con=arr>30
print(arr[con])

[40 50]


# Slicing

In [ ]:
### slicing of numpy arrays  is same as lists 
### But slicing returns the original array not copy of the array. or returns not copy.


In [60]:

arr

array([10, 20, 30, 40, 50])

In [61]:
new=arr[:2]
new

array([10, 20])

In [62]:
new[1]=90
print("change happpened in arr : " ,arr)
print(" change also happened in new :",new)


change happpened in arr :  [10 90 30 40 50]
 change also happened in new : [10 90]


In [ ]:
## use slice.copy() to get a copy of that array part avoiding referring to same array rather creates a new copy of sl

In [64]:
new=arr[:2].copy()
new

array([10, 90])

In [65]:
new[1]=100
print(" changes in new :")
print(new)
print("no change in original array :")
print(arr)

 changes in new 
[ 10 100]
no change in original array :
[10 90 30 40 50]


#                                          Multi Indexing and single Indexing and slicing


In [3]:
arr=np.array([
    [1,2,3],
    [4,5,6]
])

arr[:,0]=9
arr

array([[9, 2, 3],
       [9, 5, 6]])

# single indexing : Accesing single index 

In [9]:
#1-D Array
arr=np.array([1,2,3])
print(" 1-D Array Element : ",arr[0])
#2-D Array
arr=np.zeros((3,4))
arr[2][3]=10
print(" 2-D Array : ")
print(arr)
#3-D Array
arr=np.array(
    
    [
        
        [   
            [  1,  2,  3],

            [4,5,6]
        ],
        [
            [7,8,9],
            
            [10,11,12]
        ]
    ]
)
'''
arr=np.array(
    
    [
        #depth
        [   #row
            [ #col 1,  2,  3],

            [4,5,6]
        ],
        [
            [7,8,9],
            
            [10,11,12]
        ]
    ]
)

'''
print(" 3-D Array Element : ",arr[0,0,0])
# a 3d array is nothing but array of 2darrays
# 3d arrays elements are nothing but 2d array
# depth specifies which 2d array .
#depth - 0 (1st 2d array)
#row   - 0 (1st row)
#col   - 0(1st column)

 1-D Array Element :  1
 2-D Array : 
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0. 10.]]
 3-D Array Element :  1


# Mulitple Index or Fancy Indexing :
### Accesing multiple indices , But these indices need not be continuous or no need to constitute a part.
###                    Mention all Indices  num[ [ind1 , ind2, ....,indn] ]
###                      or num[ [list of indices ] ] always multiple indices should be given as a list.

## 2D Array: arr[ [row_indices], [col_indices] ]

## 3D Array: arr[ [depth_indices], [row_indices], [col_indices] ]

In [10]:
oneD =np.array([1,2,3,4,5,6,7,8,9])
twoD =np.array([
    [1,2,3],
    [4,5,6]
])
threeD=np.array(
    [
      [
        [1,2,3],
        [4,5,6]
    ]
])
#1-D Array
print("1-D Array Elements : ", oneD[[0,2,6]])

#2-D Array
print("2-D Array Elements : ",twoD[[0,1],[1,2]])
#3-D Array
print("3-D Array Elements : ", threeD[ [0,0 ], [0,1],[0,0]  ])

1-D Array Elements :  [1 3 7]
2-D Array Elements :  [2 6]
3-D Array Elements :  [1 4]


# Slicing :
### Accesing Multiple Indices but they need to be continuous or range of indices . 
### Mention only start and end and also step
### For 1-D Array arr[start: end : step]
### For 2-D Array      arr[
###                       start_in_x_axis: end_in_x_axis: step_in_x_axis  ,   (row)
###                       start_in_y_axis : end_in_y_axis: step_in_y_axis      (col)
###                        ]
### For 3-D Array      arr[
###                       start_in_x_axis: end_in_x_axis: step_in_x_axis  ,    (depth)
###                       start_in_y_axis : end_in_y_axis: step_in_y_axis  ,    (row)
###                       start_in_z_axis :end_in_z_axis : step_in_z_axis      (col)
###                        ]


In [11]:
print(" 1-D Array Elements slice : ", oneD[0:2:1])
#2-D Array
print("2-D Array Elements slice : ",twoD[:,1:])
#3-D Array
print("3-D Array Elements slice : ", threeD[0,1,:])

 1-D Array Elements slice :  [1 2]
2-D Array Elements slice :  [[2 3]
 [5 6]]
3-D Array Elements slice :  [4 5 6]


# Slicing + Indexing 

# Indexing when arr[row,col]
# slicing when arr[row : , col] or arr[row,col:] or arr[:,:]
# to be slicing it should definitely have a : in 2d or nd arrays

In [3]:
arr=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
#indexing +slicing
print("Indexing not slicing ")
#here 1 in row is an index not slicing.
print(arr[1,1:])
print("Slcing")
print(arr[1:,1:])


Indexing not slicing 
[6 7 8]
Slcing
[[ 6  7  8]
 [10 11 12]]


## Changing Data types

#### Common Data Types in NumPy:
#### int32, int64: Integer types with different bit sizes.
#### float32, float64: Floating-point types with different precision.
#### bool: Boolean data type.
#### complex64, complex128: Complex number types.
#### object: For storing objects (e.g., Python objects, strings).
#### You can check the dtype of a NumPy array using the .dtype attribute.

##                          Broadcasting in Numpy

#### . Broadcasting lets you add or perfrom any operation b/w two vectors or scalar + vector 
#### . when dimensions are same no problem it is easily addable or perform any operation.
#### . when dimesnions doesn't match for only some arrays which are compatable to rules.
#### . smaller shape gets stretched to larger shape by copying or stretching or row wise or col wise or both.

### performing an vector + scalar or vactor + vector operation using Broadcasting we can easily perform using Numpy.
### operator can be operator + , * ,-  
### operations must be Mathematically True.

# Scalar and vector operation

In [3]:
# there is no problem in scalar and vector operation.
arr=np.array([1,2,3])
# here same larger array shape is created using scalar
# [10,10,10] is created.
print(arr+10)

[11 12 13]


In [5]:
# for 2-D Array
twoD=np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
# scalar is copied and stretched to larger shape array.
# [
#     [10,10,10],
#     [10,10,10],
#     [10,10,10]
# ]
print(twoD+10)


[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [6]:
# for 3-D Array
threeD=np.array(
    [
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ]
    ]
)
# here scalar is stretched to a 3-D Array 
# and this stretching is nothing but broadcasting.
# [
#   [
#     [10, 10 ,10] ,
#     [10, 10, 10],
#     [10, 10, 10],
#   ]
# ]
threeD+10

array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

# vector and vector operation

### To Perform vector operations.
### both Dimensions must be compatable.

## Broadcasting Compitable Rules :
## 1. when vectors dimensions are equal. i.e ( m1== m2  and n1==n2).
## 2. when Dimensions are not equal 
## case -1 : m1 not equal to m2
## case -2 : n1 not equal to n2
## In both cases when they are not eaual one of them either m1 or m2 must be 1 (same in case 2)
## then only they are compatable for broadcasting .



#### when stretching happen in row wise all values are copied with same row.
#### when stretching happens in col wise all values are copied with same col.

In [7]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
# m1=3 ,n1= 3
# m2=1, n2=3
# they are cmpatible 
# as one of them m1 and m2 is 1 and n1=2
row_vector = np.array([1, 2, 3])

# NumPy takes [1, 2, 3] and stacks it 3 times to match the matrix height
result = matrix + row_vector

print(result)
# Row 1: [10+1, 20+2, 30+3]
# Row 2: [40+1, 50+2, 60+3]
# Row 3: [70+1, 80+2, 90+3]

[[11 22 33]
 [41 52 63]
 [71 82 93]]


In [8]:
col = np.array([[1], 
                [2], 
                [3]]) # Shape (3, 1)

# m1= 3 and n1=1
# m2= 1 and n2=3
# m1 not equal to m2 but m2=1 so it is compatible in row wise so stretch row wise.
# n1 is not equal to n2 but n1=1 so it is compatible in row wise so stretch col wise.
row = np.array([10, 20, 30]) # Shape (1,3)

result = col + row
print(result)

# What happened?
# 10+1  20+1  30+1
# 10+2  20+2  30+2
# 10+3  20+3  30+3

[[11 21 31]
 [12 22 32]
 [13 23 33]]


# Finding Mean, standard devaiation also Normalization using Broadcasting

In [10]:
data=np.array([
    [10,  104,  1010],
    [20,  222,  2230],
    [30,  343,  3140]
])

# Calcualtes mean in col wise or feature wise. because axis=0 means col wise.
# axis=0 means operation happens to same col values only.
# mean for each col values or mean calculated for their corresponding feature wise.

mean=np.mean(data , axis=0)
print("Mean :", mean)

std=np.std(data ,axis=0)
print("Standard Deviation :",std)

NormalizedData=(data-mean)/std
print(" After Normalization ")
NormalizedData


Mean : [  20.          223.         2126.66666667]
Standard Deviation : [  8.16496581  97.57390361 872.63330723]
 After Normalization 


array([[-1.22474487, -1.21958839, -1.27965167],
       [ 0.        , -0.01024864,  0.11841553],
       [ 1.22474487,  1.22983703,  1.16123614]])